### ISSUE TITLE
谱包含多个音乐文件时播放了错误的音乐文件

### ISSUE THREAD

**Issue by Ghosin** [111116/osu#1]
* map: https://osu.ppy.sh/beatmapsets/859515#osu/2082018
* mod: NONE
* version: v1.3.7.

**Comment by Ghosin** [comment]
开 auto 会黑屏...

**Comment by 111116** [comment]
疑似不规范谱面

> normalSet and additionSet can be any of the following:
>  0: No custom sample set
>       For normal sounds, the set is determined by the timing point's sample set.
>       For additions, the set is determined by the normal sound's sample set.
>   1: Normal set
>   2: Soft set
>   3: Drum set

该谱面指定的normalSet为43
