### ISSUE TITLE
跨域请求被拦截

### ISSUE THREAD

**Issue by frankli0324** [111116/osu#10]
请求api.osugame.online时会被CORS拦截
```
Access-Control-Allow-Origin: https://api.osugame.online
```

**Comment by 111116** [comment]
你这是send还是fetch

**Comment by frankli0324** [comment]
send

**Comment by 111116** [comment]
send没有返回内容，被拦截了也没关系

**Comment by 111116** [comment]
send没有返回内容，被拦截了也没关系

**Comment by frankli0324** [comment]
![image](https://user-images.githubusercontent.com/20221896/74600093-12a8fc80-50c7-11ea-87e6-a8d0d4114eb2.png)
还是有一点关系的（逃

**Comment by frankli0324** [comment]
btw，有没有让ppy康一康的想法？

**Comment by 111116** [comment]
据说ppy不喜欢别人搞osu？
