### ISSUE TITLE
some issue on macOS

### ISSUE THREAD

**Issue by ChingCdesu** [111116/osu#11]
1. Mac 上 f11并不能进入全屏 。
2. 在窗口大小改变的时候，cpu占用极高。
3. Safari 无法加载Hit Sounds
4. 某些beatmap难度列表过长

**Comment by 111116** [comment]
1. 浏览器的问题
2. 不影响使用
3. Safari不让自动播放
4. 谱包就有这么多谱

**Comment by 111116** [comment]
Chrome按cmd+shift+f可全屏

**Comment by ChingCdesu** [comment]
f11不是浏览器的问题8，firefox和chrome都不行。chrome自带的全屏，也只是把chrome本身全屏。
Safari如果不能支持也无所谓。谱面多，只能最后做优化，做一个折叠了。

**Comment by 111116** [comment]
你要点左上角的绿的按钮

**Comment by ChingCdesu** [comment]
表示没什么变化。
不过已经很完善了，作者tql

**Comment by 111116** [comment]
加了全屏按钮！在右上角，看不到的话刷新一下
