### ISSUE TITLE
無法使用 Chrome 遊玩

### ISSUE THREAD

**Issue by LianSheng197** [111116/osu#12]
### 錯誤訊息：
```
Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
```

### 錯誤
**Google Chrome** Version 80.0.3987.106 (Official Build) (64-bit) **(目前最新)**
![image](https://user-images.githubusercontent.com/18535495/74615444-bf34be00-515b-11ea-92f2-53118f3d9d7f.png)

**Chromium** Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
![image](https://user-images.githubusercontent.com/18535495/74615455-dffd1380-515b-11ea-8406-a4bbacaee933.png)

### 正常（對照）
**Firefox Browser** 73.0 (64-bit)
![image](https://user-images.githubusercontent.com/18535495/74615459-ea1f1200-515b-11ea-9fcf-541386c99900.png)

**Epiphany** 3.28.6
![image](https://user-images.githubusercontent.com/18535495/74615477-29e5f980-515c-11ea-954c-a2d78bfbca20.png)

**Comment by 111116** [comment]
[检查你的浏览器是否支持WebGL](https://get.webgl.org/)
如果这个网页也显示不支持的话，你可能需要检查你的浏览器设定

**Comment by 111116** [comment]
增加了WebGL功能验证，验证不通过会弹窗提醒。
（清除缓存以确保获取到的是最新脚本）
