### ISSUE TITLE
Consider using Websocket with localhost server for low latency input capture and audio rendering

### ISSUE THREAD

**Issue by Simakeng** [111116/osu#13]
After setting up the websocket server, I found that the typical delay from the browser to the server is 0.21ms. This should be enough for the game like _osu!_ .
I wrote this Websocket server in C #. If you use other compiled languages, there should be room for improvement.

![UKJRSJNRRE19Q J3GY5~(6Y](https://user-images.githubusercontent.com/20399522/74677223-b5aa6500-51f2-11ea-8c96-b61d40887c06.png)
![SO`VMVXE14XDI14$6C$EWPK](https://user-images.githubusercontent.com/20399522/74677224-b7742880-51f2-11ea-8b61-9da8979cee4d.png)
![$5V%BK(TBS5X8W{433ZJ(U8](https://user-images.githubusercontent.com/20399522/74677289-d8d51480-51f2-11ea-8ef7-4f849936051b.png)

**Comment by 111116** [comment]
Is this a round-trip latency?

**Comment by Simakeng** [comment]
Yes, the round-trip latency is about 0.2 milliseconds. The data I sent was 12 bytes of text "Hello World!". My CPU is AMD Ryzen 3700x. I think polling input and audio control data via localhost loopback should have similar performance on most computers.

**Comment by 111116** [comment]
Would be useful for all web action games or other web realtime applications, though surely in this project I won't require users to install anything before playing. Maybe you could pack it into something like a browser extension? (probably with a client program. just saying, don't know anything about browser extensions)

**Comment by Simakeng** [comment]
I am not suggesting to replace the original method with the method I proposed. This localhost websocket server provides a low-latency bridge between the game and device drivers. The old input method you implemented can coexist with this.

The chrome extension just runs JavaScript in a VM with limited functionality. This limits tasks that require privileges, such as direct communication with the keyboard and mouse.

**Comment by 111116** [comment]
I'm not good at writing codes that talk to hardwares/OS. And sounds like this should be a standalone project
