### ISSUE TITLE
成绩结算FC判断bug

### ISSUE THREAD

**Issue by aiyulu1** [111116/osu#15]
![20200218144719](https://user-images.githubusercontent.com/35885206/74710873-9ac10a80-525d-11ea-98f5-369df9ca3988.png)

**Comment by 111116** [comment]
你是不是切到后台听音乐了……
因为所有更新都绑在`requestAnimationFrame`上，为了节能，在后台就会什么也不做

**Comment by aiyulu1** [comment]
> 你是不是切到后台听音乐了……
> 因为所有更新都绑在`requestAnimationFrame`上，为了节能，在后台就会什么也不做

确实是后台, 那可以close了
