### ISSUE TITLE
按太早不会miss

### ISSUE THREAD

**Issue by Kerryku** [111116/osu#18]
在一个note上从缩圈开始出现时连打，都不会出现因为按太早而出现的miss，这不osu，也不音游。

**Comment by 111116** [comment]
你在osu上试过么

**Comment by 111116** [comment]
lazer 2019.1128.0 不会miss，所以不改了

**Comment by Kerryku** [comment]
> lazer 2019.1128.0 不会miss，所以不改了

抱歉，现在因为电脑的缘故玩不了osu的客户端版本，稳定版与lazer版本都不行。
大佬能不能试一试lazer最新的2020.215.0版本，如果这个版本过早点击也不会miss只会50的话，那能不能添加一个抖动，印象中按太早是会出现抖动的。

**Comment by 111116** [comment]
不想加了 太麻烦了

**Comment by Kerryku** [comment]
> 不想加了 太麻烦了

好的，辛苦了
