### ISSUE TITLE
一首歌显示出问题

### ISSUE THREAD

**Issue by Kerryku** [111116/osu#24]
Depopulated Zone-VacuumTrack
这首歌在首页会这样显示
![TIM截图20200224164035](https://user-images.githubusercontent.com/61208464/75138302-d871d780-5724-11ea-949d-3099fb0437ab.jpg)
Depopulated Zone-VacuumTrack [undefined] | undefinedx | NaN | undefined |   | NaN:

**Comment by 111116** [comment]
是你自己玩的吗？能不能看下具体是哪个mapper，因为有同名谱

**Comment by 111116** [comment]
哦我知道是哪个了
