### ISSUE TITLE
一些歌搜索不了

### ISSUE THREAD

**Issue by Kerryku** [111116/osu#25]
比如搜索
Don't say "lazy" (Full ver.)
Hisaka Yokomapped by DJPop这首歌关键词Don't say "lazy"
包含了"lazy"搜索界面就会空白
同时如果有玩家游玩了这一首铺面并且结算出现在了首页，其他玩家点击这首歌想要游玩的时候会出现undefined

**Comment by Kerryku** [comment]
点击其他玩家结算在首页的大黑也会出现这个问题

**Comment by 111116** [comment]
大部分谱不会这样，少部分谱在osu文件里没有写自己的sid

**Comment by 111116** [comment]
c5653459a1f058 33cc697e3cc43
