### ISSUE TITLE
支持自定义皮肤

### ISSUE THREAD

**Issue by andy8yue** [111116/osu#28]
主要是这个转盘很影响判断，影响游戏体验

**Comment by 111116** [comment]
影响判断指哪方面

**Comment by andy8yue** [comment]
转盘中间有个蓝色的圆形，大小和note差不多，每次转盘提前出现看到这个圆形就以为是note

**Comment by 111116** [comment]
对着lazer抄的

**Comment by andy8yue** [comment]
因为很久没玩了不知道lazer是这样的。很不习惯这个转盘，如果能自定义皮肤换掉就好了

**Comment by 111116** [comment]
但是转盘的绘制是hardcoded的，最多只能换个贴图。

**Comment by andy8yue** [comment]
希望能换成中间一个比较小的点的，比如像差异的皮肤里的

**Comment by 111116** [comment]
默认皮肤是压在spritesheet里的。如果你有时间的话，可以参照 `sprites.json` 把一些你喜欢的或者比较流行的皮肤做成spritesheet，在你本地测试一下。测试好了提交给我们，之后会考虑添加。

**Comment by andy8yue** [comment]
这个我完全不懂。。
