### ISSUE TITLE
Add touchscreen support

### ISSUE THREAD

**Issue by MTGPROD** [111116/osu#29]
We can't interact with the game in mobile web browsers.

**Comment by Deardrops** [comment]
Hi, here this a PR #21 try to add touchscreen support, but meet some compatibly issues.

**Comment by 111116** [comment]
Mobile browsers get too many performance & compatibility issues so we don't do that. On other touchscreens (like Surface) might be possible although there aren't too many users.
And I'm not working on this project as often as before. If you're interested check out test page of PR #21:  http://simshop.po-i.cc:8117/osu/

**Comment by MTGPROD** [comment]
That lost the interest of a osu in a web browser :/
