### ISSUE TITLE
crash on marathon maps 

### ISSUE THREAD

**Issue by ts8zs** [111116/osu#34]
example: https://osu.ppy.sh/beatmapsets/1125283

**Comment by 111116** [comment]
I just launched the map without a problem. Did that crash halfway when playing or just failed loading?

**Comment by ts8zs** [comment]
failed loading,maybe cause by left memory is low?

**Comment by 111116** [comment]
try looking at browser console?

**Comment by ts8zs** [comment]
https://ufile.io/y3kx0j3l
https://ufile.io/1t01abfk

**Comment by 111116** [comment]
Umm.. Firefox task manager shows that this map takes 475MB on my computer, which shouldn't be a big deal. I actually have no idea what's going wrong there

**Comment by ts8zs** [comment]
firefox also works fine for me.I think this is vivaldi's fault.
