### ISSUE TITLE
Unable to load hitsounds on iOS  devices 无法在苹果移动设备上载入hitsounds

### ISSUE THREAD

**Issue by Chen-Junze** [111116/osu#35]
I am an iOS device user and I ran into a problem that happens on **all of my iOS devices**. On Safari browser, when I open the site, the hitsounds loading status freezes on that "loading circle" but my iPad status bar suggests that no internet activity is in progress(no loading icon). Please fix this as this is really bad.

我是一个iOS设备用户，而近期我遇到了一个发生在我所有iOS设备上的问题。在系统自带的Safari浏览器里，当我打开网站时，hitsounds的加载状态一直卡在“转圈”，但是我的iPad的状态栏显示目前没有网络活动（没有转圈）。这问题很严重，请尽快修复。蟹蟹。

**Comment by 111116** [comment]
不支持移动设备。请使用桌面端浏览器
