### ISSUE TITLE
手机端帧率低

### ISSUE THREAD

**Issue by RERASER** [111116/osu#38]
Android 8.1.0; vivo X20 Chrome/73.0.3683.0 Mobile Edge/44.11.2.4122
分辨率无论是降到最低还是拉到最高，帧率是差不多的，所以感觉不是分辨率问题

**Comment by 111116** [comment]
你是怎么在手机上玩的……

**Comment by RERASER** [comment]
触控不能用，OTG鼠标可以

**Comment by 111116** [comment]
太猛了 我都没想过有人会在手机上玩这玩意

**Comment by RERASER** [comment]
开硬件光标后光标就消失了，所以会不会是绘图用的CPU绘的。。。

**Comment by 111116** [comment]
那个是css的pointer，因为各种浏览器的css光标支持有各种奇奇怪怪的bug，所以默认关了

**Comment by RERASER** [comment]
开了悬浮窗，cpu和gpu都没吃满，使用qboost强行拉满cpu和gpu的话帧率也没提升。。。

**Comment by 111116** [comment]
你确定帧率低是整个画面低，而不是只有光标帧率低？

**Comment by RERASER** [comment]
整个画面帧率低，光标除了有点延迟帧率是够的

**Comment by 111116** [comment]
我不知道 手机上能开浏览器的性能分析么

**Comment by RERASER** [comment]
应该可以连电脑进行调试吧

**Comment by RERASER** [comment]
尝试使用了正式版的Chrome,除了支持了硬件光标，帧率并无提升

**Comment by 111116** [comment]
嘛总之这项目从来没支持过移动端
