### ISSUE TITLE
Audio offset 设置疑似不起作用

### ISSUE THREAD

**Issue by Tsuk1ko** [111116/osu#4]
调 offset 的过程中发现怎么调都感觉不到差别，试着分别调到 +80 和 -80 并只注意听歌不在意判定圈各打了一把，确实没有差别

是因为这项功能仍在 TODO 吗

**Comment by 111116** [comment]
是的，还没有实现，因为还没有和玩家交流过这一功能。
浏览器本身具有输入延迟，并且目前可能仍有一小部分谱面有时间同步的问题。
如果你在大部分谱面上注意打击声和音乐对齐时，判定都有明显的偏移（参照结算页面的Hit error），请继续回复我。
