### ISSUE TITLE
连接被重置

### ISSUE THREAD

**Issue by PercyDan54** [111116/osu#43]
搜索别的谱没问题，就是搜FD会显示连接被重置，要等2分钟才能再进去
[![tfqwvT.png](https://s1.ax1x.com/2020/06/08/tfqwvT.png)](https://imgchr.com/i/tfqwvT)

**Comment by 111116** [comment]
破事水

**Comment by PercyDan54** [comment]
> 
> 
> 破事水

咋就氵了。。。

**Comment by xdd44-utopia** [comment]
富强、**、文明、和谐、自由、平等、公正、法治、爱国、敬业、诚信、友善。

**Comment by xdd44-utopia** [comment]
富强、民主、文明、和谐、**、平等、公正、法治、爱国、敬业、诚信、友善。
