### ISSUE TITLE
skin support

### ISSUE THREAD

**Issue by venomthor2** [111116/osu#47]
i really like osu web (its also the only way i can play osu) but there is only one problem and its no skin support i cant play that much well with the lazer skin

**Comment by 111116** [comment]
no skinning support is planned. PRs are welcomed though.

**Comment by venomthor2** [comment]
just a suggestion: choose some skins (most likely popular osu skins like yugen ,vaxei ,merami skins) like in the korean translation which has the kr in the front of the link maybe make like in front of the link the skin name or something like skin1 skin2 just a stupid suggestion i had rn
