### ISSUE TITLE
游戏无法进行

### ISSUE THREAD

**Issue by cleeelee** [111116/osu#5]
左上角显示谱面已下载,音效和皮肤长时间处于加载中
光标选择难度时显示繁忙(转圈)无法进入

**Comment by cleeelee** [comment]
尝试多个谱面都是如此

**Comment by 111116** [comment]
检查浏览器开发者工具里的控制台有无报错；切换到浏览器开发者工具里的网络标签并按提示刷新，查看是否有http错误码或长时间未响应的请求

**Comment by cleeelee** [comment]
> 检查浏览器开发者工具里的控制台有无报错；切换到浏览器开发者工具里的网络标签并按提示刷新，查看是否有http错误码或长时间未响应的请求

其实不太懂这些,,, 不过现在上面的问题都正常加载了 但是依然无法进入 选择难度无反应
呃 照你的说法 点选难度后跳出两个.js文件 响应时间都在70ms左右 其他的好像没什么了

**Comment by cleeelee** [comment]
> 检查浏览器开发者工具里的控制台有无报错；切换到浏览器开发者工具里的网络标签并按提示刷新，查看是否有http错误码或长时间未响应的请求

刷新了一下 正常加载后 选难度后跳出几个error

Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
这个错误在我每选一次难度后就出现一次 下面还有一大串码不知道有没有必要发

**Comment by 111116** [comment]
请使用最新版Firefox或Chrome
