### ISSUE TITLE
Scroll Wheel does not work when in the game menus

### ISSUE THREAD

**Issue by ReNForce72** [111116/osu#71]
**Describe the bug**
Pretty self-explanatory (though the issue might not be so easy to figure out). Scrolling to adjust volume works fine in-game, but I've never been able to scroll when in the menu; I've always needed to drag the sidebar down to scroll manually with the cursor.

**Console error**
n/a

**Desktop (please complete the following information):**
- OS: macOS (Mojave 10.14.6)
- Browser: Chrome (Version 90.0.4430.93 (Official Build) (x86_64))

**Comment by 111116** [comment]
what menu?

**Comment by ReNForce72** [comment]
By menu, I just mean every aspect of the website that isn't the 'game' (searching for beatmaps, changing setup preferences, etc.)

**Comment by 111116** [comment]
You mean the webpage scrolling never works? This is really weird, as I've tested on different computers (including Chrome on a macbook) and never found this issue.

**Comment by ReNForce72** [comment]
https://user-images.githubusercontent.com/83483901/117240389-52582300-adf6-11eb-8072-8751e72f9fad.MOV

I started playing way back in October 2020, and as far as I can remember, it's always been like this (I just now found this forum)
I should mention I'm running my mac to a monitor with a thunderbolt adapter (that doesn't change anything though)

**Comment by ReNForce72** [comment]
I figured it out; I just tried it in incognito mode and it worked fine. That's when I realized I had a chrome extension that changes how scrolling works. I uninstalled it and it works fine now, totally my bad.
