### ISSUE TITLE
api.osugame.online hosted on HTTP

### ISSUE THREAD

**Issue by BlaNKtext** [111116/osu#73]
**Describe the bug**
`http://api.osugame.online` is not hosted on `https`, breaking `https://osugame.online`s "What Happened" feature. (It does still work on `http://osugame.online`)

**Console error**
(index):206 Mixed Content: The page at 'https://osugame.online/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.osugame.online/fetch/'. This request has been blocked; the content must be served over HTTPS.

**Desktop**
 - OS: Chrome OS (This doesn't affect anything)
 - Browser: Chrome
 - Version: Latest

**Comment by 111116** [comment]
yep. for now you can visit http://osugame.online (without TLS). TLS may be configured in future

**Comment by BlaNKtext** [comment]
> yep. for now you can visit http://osugame.online (without TLS). TLS may be configured in future

Ok! I wasn't quite sure if this had been acknowledged as it seems this project is semi-dead but I am glad to know that is not the case

(Also moving to https can be done for free in roughly 10 minutes with cloudflare!)

**Comment by 111116** [comment]
yeah this project is indeed almost dead now because of my laziness
