### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by JMcrafter26** [111116/osu#96]
**Describe the bug**
Settings won't save. If I change the settings and then refresh the page, they are reset. I also noticed, that the default settings from the settings.js are not applied. Am I the only one with this issue?

**Console error**
No errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 22

**Comment by BlaNKtext** [comment]
Try chrome, or try webosu.online

**Comment by JMcrafter26** [comment]
I tried chrome and even from my mobile, but it didn't worked. I host it on my server and I am using the latest version
